logo: Logo-02.png

author: Cristian Darío Ortega Yubro

Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
    
avatar: "/assets/img/avatar-icon.png"
round-avatar: true
