theme: jekyll-theme-hacker
title: cristian darío ortega yubro
description: Ruta de aprendizaje Python

author: "Cristian Darío Ortega Yubro"
theme_repository: "https://github.com/pages-themes/hacker"
        
github: 
  " "
  
#logo: img/Logo-02.png
