theme: jekyll-theme-hacker
title: cristian darío ortega yubro
description: Google Colab Python

show_downloads: False
Github: False

author: Cristian Darío Ortega Yubro
theme_repository: https://github.com/pages-themes/hacker
        
github:  
  
#logo: img/Logo-02.png
